title: Scikit-HEP
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/tmp-scikithep-website"
url: "https://henryiii.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# Local: theme: "just-the-docs"
remote_theme: "pmarsceill/just-the-docs"
plugins:
  - jekyll-feed

# Theme settings

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
    "Scikit-HEP on GitHub":
      - "//github.com/scikit-hep"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
