title: Scikit-HEP
email: your-email@example.com
description: >-
  The Scikit-HEP project is a community-driven and community-oriented
  project with the aim of providing Particle Physics at large with an
  ecosystem for data analysis in Python. The project started in Autumn
  2016 and is under active development.
baseurl: "/tmp-scikithep-website"
url: "https://henryiii.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# Local: theme: "just-the-docs"
remote_theme: "pmarsceill/just-the-docs"
plugins:
  - jekyll-feed

# Theme settings

# Enable or disable the site search
search_enabled: false

# Aux links for the upper right navigation
aux_links:
    "Scikit-HEP on GitHub":
      - "//github.com/scikit-hep"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
